#version 460
#include "../common/params.glsl"

layout(local_size_x = 256) in;
void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.numParticles) return;

    if (w[i] == 0.0) {
        deltaX[i] = 0.0; deltaY[i] = 0.0; deltaZ[i] = 0.0; dcount[i] = 0u;
        return;
    }
    uint c = max(dcount[i], 1u);
    vec3 corr = vec3(deltaX[i], deltaY[i], deltaZ[i]) / c;
    x[i].xyz += corr;
    
//    deltaX[i] = 0.0; deltaY[i] = 0.0; deltaZ[i] = 0.0; dcount[i] = 0u;
}