#version 460
#include "../common/params.glsl"

layout(local_size_x = 256) in;
void main(){
    uint id = gl_GlobalInvocationID.x;

    if (id < sim.num_particles) {
        delta_x[id] = 0.0;
        delta_y[id] = 0.0;
        delta_z[id] = 0.0;
        delta_count[id] = 0;
    }

    if (id < sim.num_edges) edges[id].lambda = 0.0;
    if (id < sim.num_bends) bends[id].lambda = 0.0;
    if (id < sim.num_shears) shears[id].lambda = 0.0;
    if (id < sim.num_areas) areas[id].lambda = 0.0;
}