#version 460
#include "../common/params.glsl"

layout(local_size_x = 256) in;
void main(){
    uint i = gl_GlobalInvocationID.x;

    if (i < sim.num_particles) {
        delta_x[i] = 0.0;
        delta_y[i] = 0.0;
        delta_z[i] = 0.0;
        delta_count[i] = 0;
    }

    if (i < sim.num_edges) edges[i].lambda = 0.0;
    if (i < sim.num_bends) bends[i].lambda = 0.0;
    if (i < sim.num_shears) shears[i].lambda = 0.0;
    if (i < sim.num_areas) areas[i].lambda = 0.0;
}