#version 460

#include "../common/params.glsl"

layout(local_size_x = 256) in;

float sdf_sphere(vec3 p, vec3 center, float radius)
{
    return length(p - center) - radius;
}

vec3 normal_sphere(vec3 p, vec3 center)
{
    return normalize(p - center);
}

float sdf_plane(vec3 p, vec3 pointOnPlane, vec3 normal)
{
    return dot(normal, p - pointOnPlane);
}

vec3 normal_plane(vec3 p, vec3 normal)
{
    return normal;
}

float sdf_capsule(vec3 p, vec3 a, vec3 b, float radius)
{
    vec3 pa = p - a;
    vec3 ba = b - a;
    float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    vec3 closest = a + h * ba;
    return length(p - closest) - radius;
}

vec3 normal_capsule(vec3 p, vec3 a, vec3 b)
{
    vec3 pa = p - a;
    vec3 ba = b - a;
    float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
    vec3 closest = a + h * ba;

    vec3 d = p - closest;
    float len = length(d);
    if (len < 1e-6) return vec3(0.0, 1.0, 0.0);
    return d / len;
}

vec3 compute_friction(vec3 correction, vec3 relMove, vec3 n, float friction)
{
    if (friction <= 0.0)
        return vec3(0.0);

    vec3 t = relMove - dot(relMove, n) * n;
    float len_t = length(t);
    if (len_t < 1e-6)
        return vec3(0.0);

    float k = max(0.0, 1.0 - friction);
    vec3 t_new = t * k;

    vec3 d_new = dot(relMove, n) * n + t_new;
    vec3 friction_corr = d_new - relMove;
    return friction_corr;
}

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id >= sim.num_particles) return;

    float w_i = w[id];
    if (w_i == 0.0) return;

    vec3 x_prev = x[id].xyz;
    vec3 x_pred = xp[id].xyz;

    float dt = sim.dt;

    for (uint i = 0; i < sim.num_colliders; i++)
    {
        Collider col = colliders[i];

        vec3 p0   = col.p0;
        float rad = col.radius + sim.thickness;
        vec3 p1   = col.p1;
        int kind  = col.kind;

        float C = 0.0;
        vec3 n  = vec3(0.0);

        if (kind == 0) {          // sphere
            C = sdf_sphere(x_pred, p0, rad);
            if (C < 0.0) n = normal_sphere(x_pred, p0);
        }
        else if (kind == 1) {     // plane
            C = sdf_plane(x_pred, p0 + vec3(sim.thickness), normalize(p1));
            if (C < 0.0) n = normalize(p1);
        }
        else if (kind == 2) {     // capsule
            C = sdf_capsule(x_pred, p0, p1, rad);
            if (C < 0.0) n = normal_capsule(x_pred, p0, p1);
        }

        if (C < 0.0) {
            // normal correction
            vec3 corr_n = -C * n;
            x_pred += corr_n;

            // friction
            vec3 relMove = x_pred - x_prev;
            vec3 corr_f = compute_friction(corr_n, relMove, n, sim.friction);
            x_pred += corr_f;
        }

    }

    xp[id] = vec4(x_pred, xp[id].w);
}
