#version 460
#include "../common/params.glsl"

layout(local_size_x = 256) in;
void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.numVerts) return;
    if (w[i] == 0.0) return;

    vec3 p = x[i].xyz;
    vec3 d = p - sim.sphereCenter.xyz;
    float dist = length(d);

    if (dist < sim.sphereRadius) {
        vec3 n = (dist > 1e-8) ? (d / dist) : vec3(0, 1, 0);
        p += (sim.sphereRadius - dist) * sim.collisionBeta * n;
        x[i].xyz = p;
    }
}