#version 460

#include "../common/params.glsl"

layout(local_size_x = 256) in;

float sdf_sphere(vec3 p, vec3 center, float radius)
{
    return length(p - center) - radius;
}

vec3 normal_sphere(vec3 p, vec3 center)
{
    return normalize(p - center);
}

float sdf_ground(vec3 p, float gy)
{
    return p.y - gy;
}

vec3 normal_ground(vec3 p)
{
    return vec3(0.0, 1.0, 0.0);
}

vec3 compute_friction(vec3 correction, vec3 relMove, vec3 n, float friction)
{
    if (friction <= 0.0)
        return vec3(0.0);

    vec3 t = relMove - dot(relMove, n) * n;
    float len_t = length(t);
    if (len_t < 1e-6)
        return vec3(0.0);

    float k = max(0.0, 1.0 - friction);
    vec3 t_new = t * k;

    vec3 d_new = dot(relMove, n) * n + t_new;
    vec3 friction_corr = d_new - relMove;
    return friction_corr;
}

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id >= sim.num_particles) return;

    float w_i = w[id];
    if (w_i == 0.0) return;

    vec3 x_prev = x[id].xyz;
    vec3 x_pred = xp[id].xyz;

    float dt = sim.dt;

    {
        float C = sdf_sphere(x_pred,
                             sim.sphere_center.xyz,
                             sim.sphere_radius + sim.thickness);

        if (C < 0.0) // penetration
        {
            vec3 n = normal_sphere(x_pred, sim.sphere_center.xyz);

            vec3 corr_n = -C * n;
            x_pred += corr_n;

            vec3 relMove = x_pred - x_prev;
            vec3 corr_f = compute_friction(corr_n, relMove, n, sim.friction);
            x_pred += corr_f;
        }
    }

    {
        float Cg = sdf_ground(x_pred, 0.0 + sim.thickness);
        if (Cg < 0.0)
        {
            vec3 n = normal_ground(x_pred);

            // normal correction
            vec3 corr_n = -Cg * n;
            x_pred += corr_n;

            // friction
            vec3 relMove = x_pred - x_prev;
            vec3 corr_f = compute_friction(corr_n, relMove, n, sim.friction);
            x_pred += corr_f;
        }
    }

    xp[id] = vec4(x_pred, xp[id].w);
}
