#version 460

#include "../common/params.glsl"

layout(local_size_x = 256) in;

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id >= sim.num_particles)
        return;

    vec3 xi  = x[id].xyz;
    vec3 xpi = xp[id].xyz;
    
    float d = length(xpi - sim.sphere_center.xyz);
    if (d < sim.sphere_radius + sim.thickness){
        vec3 p = mix(xpi, xi, sim.friction);
        vec3 r = p - sim.sphere_center.xyz;
        float d = length(r);
        xpi = sim.sphere_center.xyz + r * ((sim.sphere_radius + sim.thickness) / d);
    }
    if (xpi.y < sim.thickness){
        vec3 p = mix(xpi, xi, sim.friction);
        xpi = vec3(p.x, sim.thickness, p.z);
    }

    xp[id].xyz = xpi;
}
