#version 460
#include "../common/params.glsl"
layout(local_size_x = 256) in;
void main(){
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.num_particles) return;
    
    vec3 xi = x[i].xyz;

    if (w[i] == 0.0) {
        xp[i] = vec4(xi, 1.0);
        v[i]  = vec4(0.0);
        return;
    }
    vec3 vi = v[i].xyz;

    vec3 wind = vec3(0);
    if (sim.wind_test==1){
        float L = length(sim.wind_dir.xyz);
        if (L>1e-8) 
            wind = (sim.wind_dir.xyz/L)*sim.wind_strength;
    }
    vi += (sim.gravity.xyz + wind) * sim.dt;
    vec3 xpi = xi + vi * sim.dt;

    xp[i] = vec4(xpi,1.0);
    v[i] = vec4(vi,0.0);
}
