#version 460
#extension GL_EXT_shader_atomic_float : require

#include "../common/params.glsl"

layout(local_size_x = 256) in;

void accumulate_delta(uint i, vec3 corr, uint count)
{
    atomicAdd(delta_x[i], corr.x);
    atomicAdd(delta_y[i], corr.y);
    atomicAdd(delta_z[i], corr.z);
    atomicAdd(delta_count[i], count);
}

vec3 compute_friction(vec3 correction_disp, vec3 rel_vel, float mu)
{
    vec3 friction = vec3(0.0);
    float correction_length = length(correction_disp);

    if (mu <= 0.0 || correction_length <= 0.0)
        return friction;

    vec3 n = correction_disp / correction_length;

    vec3 tan_vel = rel_vel - n * dot(rel_vel, n);
    float tan_length = length(tan_vel);
    if (tan_length < 1e-6)
        return friction;
        
    float max_tanLength = correction_length * mu;
    float scale = min(max_tanLength / tan_length, 1.0);

    friction = -tan_vel * scale;
    return friction;
}

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.num_particles) return;

    float wi = w[i];
    vec3  xi = xp[i].xyz;
    vec3  pxi = x[i].xyz;

    uint maxN = sim.max_neighbors;
    float r   = sim.collision_radius;

    uint base = i * maxN;

    float dt = sim.dt;

    vec3 delta_i = vec3(0.0);
    uint count_i = 0u;

    uint object_i = object_ids[i];

    for (uint k = 0; k < maxN; ++k)
    {
        uint idx = base + k;
        uint j   = neighbors[idx];

        if (j == 0xFFFFFFFFu)
            break;
            
        uint object_j = object_ids[j];

        bool same = (object_i == object_j);

        float compliance = same ? pc.solve.compliance : 0.0;
        float mu         = same ? sim.neighbor_friction : 0.0;
        float alpha_tilde = compliance / (dt * dt);

        float wj = w[j];
        if (wi + wj == 0.0)
            continue;

        vec3 xj = xp[j].xyz;
        vec3 pxj = x[j].xyz;

        vec3 d  = xi - xj;
        float d2 = dot(d, d);
        if (d2 < 1e-12)
            continue;

        float dist = sqrt(d2);

        float C = dist - r;

        if (C >= 0.0)
            continue;

        vec3 n = d / dist;

        float wsum = wi + wj;

        float lambda_old = neighbor_lambdas[idx];

        float denom = wsum + alpha_tilde;
        if (denom < 1e-8)
            continue;

        float rhs = C + alpha_tilde * lambda_old;
        float dLambda = -rhs / denom;
        float lambda_new = lambda_old + dLambda;

        neighbor_lambdas[idx] = lambda_new;

        vec3 corr_i =  wi * dLambda * n * sim.self_collision_stiffness;
        vec3 corr_j = -wj * dLambda * n * sim.self_collision_stiffness;

        vec3 vel_i = xi - pxi;
        vec3 vel_j = xj - pxj;
        vec3 relVel = vel_i - vel_j;

        vec3 commma_i = (wi > 0.0) ? (corr_i / wi) : vec3(0.0);
        vec3 friction_i = compute_friction(commma_i, relVel, mu);

        if (wi > 0.0) {
            delta_i += corr_i + wi * friction_i;
            count_i += 1u;
        }

        if (wj > 0.0) {
            vec3 delta_j = corr_j - wj * friction_i;
            accumulate_delta(j, delta_j, 1u);
        }
    }

    if (count_i > 0u) {
        accumulate_delta(i, delta_i, count_i);
    }
}
