#version 460
#extension GL_EXT_shader_atomic_float : require

#include "../common/params.glsl"

layout(local_size_x = 256) in;

void main() {
    uint eidx = gl_GlobalInvocationID.x;
    if (eidx >= uint(sim.numAllEdges)) return;

    Edge e = edges[eidx];
    uint i = e.i;
    uint j = e.j;

    float w0 = w[i];
    float w1 = w[j];
    float wsum = w0 + w1;
    if (wsum == 0.0) return;

    vec3 p0 = x[i].xyz;
    vec3 p1 = x[j].xyz;

    vec3 d = p1 - p0;
    float l = length(d);
    if (l < 1e-7) return;
    vec3 n = d / l;

    float l0 = e.rest;
    float C  = l - l0;

    vec3 corr = (C / wsum) * n * e.stiff;
    
    if (w0 > 0.0) {
        atomicAdd(deltaX[i], +w0 * corr.x);
        atomicAdd(deltaY[i], +w0 * corr.y);
        atomicAdd(deltaZ[i], +w0 * corr.z);
        atomicAdd(dcount[i], 1u);
    }
    if (w1 > 0.0) {
        atomicAdd(deltaX[j], -w1 * corr.x);
        atomicAdd(deltaY[j], -w1 * corr.y);
        atomicAdd(deltaZ[j], -w1 * corr.z);
        atomicAdd(dcount[j], 1u);
    }
}
