#version 460

#include "../common/params.glsl"

layout(local_size_x = 256) in;

void main() {
    uint triId = gl_GlobalInvocationID.x;
    if (triId >= sim.num_tries) return; // sim.num_tries = numTris

    uint i0 = indices[triId * 3 + 0];
    uint i1 = indices[triId * 3 + 1];
    uint i2 = indices[triId * 3 + 2];

    vec3 p0 = x[i0].xyz;
    vec3 p1 = x[i1].xyz;
    vec3 p2 = x[i2].xyz;

    vec3 e1 = p1 - p0;
    vec3 e2 = p2 - p0;
    vec3 fn = cross(e1, e2); // area-weighted

    if (dot(fn, fn) < 1e-20)
        tri_normals[triId] = vec4(0.0);
    else
        tri_normals[triId] = vec4(fn, 0.0);
}
