#version 460
#include "../common/params.glsl"

layout(local_size_x = 256) in;
void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.num_particles) return;

    if (w[i]==0.0) { v[i]=vec4(0.0); x[i]=xp[i]; return; }

    vec3 new_pos = xp[i].xyz;
    vec3 new_vel = (new_pos - x[i].xyz) / sim.dt;

    v[i].xyz = new_vel * (1.0f - sim.global_damping * sim.dt);
    x[i].xyz = new_pos;
}