#version 460
#include "../common/params.glsl"

layout(local_size_x = 256) in;
void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.numParticles) return;

    if (w[i]==0.0) { v[i]=vec4(0.0); x[i]=xp[i]; return; }

    vec3 newP = xp[i].xyz;
    vec3 newV = (newP - x[i].xyz) / sim.dt;
//    float vLen = length(newV);
//    if (vLen > sim.maxSpeed)
//    {
//        newV = newV / vLen * sim.maxSpeed;
//        newP = x[i].xyz + newV * sim.dt;
//    }
    v[i].xyz = newV * (1.0 - sim.damping * sim.dt);
//    v[i].xyz = newV;
    x[i].xyz = newP;
}