#version 450
layout(local_size_x = 10, local_size_y = 10, local_size_z = 1) in;

struct Particle {
    vec4 pos;
    vec4 vel;
    vec4 uv;
    vec4 normal;
};

layout(set = 0, binding = 0, std430) readonly buffer ParticleIn {
    Particle vin[];
};

layout(set = 0, binding = 1, std430) writeonly buffer ParticleOut {
    Particle vout[];
};

layout(set = 0, binding = 2, std140) uniform UBOCompute {
    float delta_time;
    float particle_mass;
    float spring_stiffness;
    float damping;
    float rest_dist_h;
    float rest_dist_v;
    float rest_dist_d;
    float sphere_radius;
    vec4  sphere_pos;
    vec4  gravity;
    ivec2 particle_count;
} params;

layout(push_constant) uniform PC {
    uint calculate_normals;
} pc;

vec3 springForce(vec3 p0, vec3 p1, float restDist)
{
    vec3 d = p0 - p1;
    float L = length(d);
    if (L < 1e-5) return vec3(0.0);
    return (d / L) * params.spring_stiffness * (L - restDist);
}

void main()
{
    uvec3 id = gl_GlobalInvocationID;
    uint idx = id.y * uint(params.particle_count.x) + id.x;

    if (id.x >= uint(params.particle_count.x) ||
        id.y >= uint(params.particle_count.y)) return;

    vec3 force = params.gravity.xyz * params.particle_mass;

    vec3 pos = vin[idx].pos.xyz;
    vec3 vel = vin[idx].vel.xyz;

    if (id.x > 0)
        force += springForce(vin[idx-1].pos.xyz, pos, params.rest_dist_h);
    if (id.x + 1 < uint(params.particle_count.x))
        force += springForce(vin[idx+1].pos.xyz, pos, params.rest_dist_h);
    if (id.y + 1 < uint(params.particle_count.y))
        force += springForce(vin[idx + uint(params.particle_count.x)].pos.xyz, pos, params.rest_dist_v);
    if (id.y > 0)
        force += springForce(vin[idx - uint(params.particle_count.x)].pos.xyz, pos, params.rest_dist_v);

    if (id.x > 0 && id.y + 1 < uint(params.particle_count.y))
        force += springForce(vin[idx + uint(params.particle_count.x) - 1].pos.xyz, pos, params.rest_dist_d);
    if (id.x > 0 && id.y > 0)
        force += springForce(vin[idx - uint(params.particle_count.x) - 1].pos.xyz, pos, params.rest_dist_d);
    if (id.x + 1 < uint(params.particle_count.x) && id.y + 1 < uint(params.particle_count.y))
        force += springForce(vin[idx + uint(params.particle_count.x) + 1].pos.xyz, pos, params.rest_dist_d);
    if (id.x + 1 < uint(params.particle_count.x) && id.y > 0)
        force += springForce(vin[idx - uint(params.particle_count.x) + 1].pos.xyz, pos, params.rest_dist_d);

    force += (-params.damping * vel);

    vec3 a = force / params.particle_mass;
    vec3 newPos = pos + vel * params.delta_time + 0.5 * a * params.delta_time * params.delta_time;
    vec3 newVel = vel + a * params.delta_time;

    vec3 sDist = newPos - params.sphere_pos.xyz;
    if (length(sDist) < params.sphere_radius + 0.01) {
        newPos = params.sphere_pos.xyz + normalize(sDist) * (params.sphere_radius + 0.01);
        newVel = vec3(0.0);
    }

    vout[idx].pos = vec4(newPos, 1.0);
    vout[idx].vel = vec4(newVel, 0.0);

    if (pc.calculate_normals == 1u) {
        vec3 normal = vec3(0);
        vec3 a1,b1,c1;
        if (id.y > 0u) {
            if (id.x > 0u) {
                a1 = vin[idx - 1].pos.xyz - pos;
                b1 = vin[idx - uint(params.particle_count.x) - 1].pos.xyz - pos;
                c1 = vin[idx - uint(params.particle_count.x)].pos.xyz - pos;
                normal += cross(a1,b1) + cross(b1,c1);
            }
            if (id.x + 1u < uint(params.particle_count.x)) {
                a1 = vin[idx - uint(params.particle_count.x)].pos.xyz - pos;
                b1 = vin[idx - uint(params.particle_count.x) + 1].pos.xyz - pos;
                c1 = vin[idx + 1].pos.xyz - pos;
                normal += cross(a1,b1) + cross(b1,c1);
            }
        }
        if (id.y + 1u < uint(params.particle_count.y)) {
            if (id.x > 0u) {
                a1 = vin[idx + uint(params.particle_count.x)].pos.xyz - pos;
                b1 = vin[idx + uint(params.particle_count.x) - 1].pos.xyz - pos;
                c1 = vin[idx - 1].pos.xyz - pos;
                normal += cross(a1,b1) + cross(b1,c1);
            }
            if (id.x + 1u < uint(params.particle_count.x)) {
                a1 = vin[idx + 1].pos.xyz - pos;
                b1 = vin[idx + uint(params.particle_count.x) + 1].pos.xyz - pos;
                c1 = vin[idx + uint(params.particle_count.x)].pos.xyz - pos;
                normal += cross(a1,b1) + cross(b1,c1);
            }
        }
        vout[idx].normal = vec4(normalize(normal), 0.0);
    }
}
