#version 460
layout(local_size_x = 256) in;

#include "common/params.glsl"

void main(){
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.numParticles) return;

    if (w[i] == 0.0) { xp[i] = xp[i]; return; }

    // 데모용: 원점 구
    vec3  c = vec3(0.0, 0.0, 0.0);
    float R = 1.0;
    if (R <= 0.0) return;

    vec3 p = xp[i].xyz;
    vec3 d = p - c;
    float dist = length(d);

    if (dist < R) {
        vec3 n = (dist > 1e-8) ? (d / dist) : vec3(0,1,0);
        float beta = 0.3;                  // 0~1 (0.2~0.5 추천)
        xp[i].xyz = p + beta * (R - dist) * n;
    }
}
