
#version 460
layout(local_size_x = 128) in;

layout(std140, set=0, binding=0) uniform Sim {
    float dt, gravity;
} U;
layout(set=1, binding=0, std430) buffer Positions { vec4 P[];  };
layout(set=1, binding=1, std430) buffer Velocities { vec4 V[];  };


void main(){
    uint id = gl_GlobalInvocationID.x;
    if (id >= P.length()) return;
    
    vec3 v = V[id].xyz;
    v += vec3(0.0, U.gravity, 0.0) * U.dt;

    vec3 p = P[id].xyz;
    p += v;

    P[id] = vec4(p, 0.0);
    V[id] = vec4(v, 0.0);
}
