
#version 460
layout(local_size_x = 256) in;

#include "common/params.glsl"

void main(){
    uint i = gl_GlobalInvocationID.x;
    if (i >= params.numParticles) return;
    
    // 고정점은 예측 위치 = 현재 위치
    if (w[i] == 0.0) {
        xp[i] = x[i];
        return;
    }

    vec3 xi = x[i].xyz;
    vec3 vi = v[i].xyz;

    // 반-스텝 중력(선형 가속)
    vi += params.gravity.xyz * params.dt;

    // 예측 위치
    xp[i].xyz = xi + vi * params.dt;
}
