#version 460
#include "../common/simulation_common.glsl"
layout(local_size_x = 256) in;

void main() {
    uint gid = gl_GlobalInvocationID.x;
    uint N   = sim.num_particles;
    if (gid >= N) return;

    uint curr = hashes[gid];
    uint prev = (gid == 0) ? 0xFFFFFFFFu : hashes[gid - 1];

    if (gid == 0 || curr != prev) {
        starts[curr] = gid;
        if (gid > 0) ends[prev] = gid;
    }
    if (gid == N - 1) ends[curr] = N;
}
