#version 460
#include "../common/params.glsl"

layout(local_size_x = 256) in;

uint hash_coords(int xi, int yi, int zi)
{
    uint h = uint(xi) * 92837111u ^
             uint(yi) * 689287499u ^
             uint(zi) * 283923481u;
    return h % sim.num_tables;
}

ivec3 int_coord(vec3 p) {
    return ivec3(floor(p / sim.cell_size));
}

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.num_particles) return;

    vec3 p = xp[i].xyz;

    ivec3 c = int_coord(p);

    uint h = hash_coords(c.x, c.y, c.z);

    hashes[i]  = h;
    indices[i] = i;
}
