#version 460
#extension GL_EXT_shader_atomic_float : require

#include "../common/simulation_common.glsl"

layout(local_size_x = 256) in;

const uint MOUSE_MODE_NONE   = 0u;
const uint MOUSE_MODE_SELECT = 1u;
const uint MOUSE_MODE_DRAG   = 2u;

void mouse_select_pass(uint i, vec3 pos)
{
    if (pc.mouse.select_mode == MOUSE_MODE_NONE) {
        grab_state[0].id       = 0xFFFFFFFFu;
        grab_state[0].t_bits   = 0xFFFFFFFFu;
        return;
    }

    if (pc.mouse.select_mode != MOUSE_MODE_SELECT)
        return;

    vec3 o   = pc.mouse.ray_origin;
    vec3 dir = pc.mouse.ray_dir;

    vec3 v = pos - o;
    float t = dot(v, dir);
    if (t <= 0.0) return;

    vec3 c = o + t * dir;
    float dist2 = dot(pos - c, pos - c);

    float r = pc.mouse.radius;
    if (dist2 > r * r) return;

    uint tBits = floatBitsToUint(t);

    uint old = atomicMin(grab_state[0].t_bits, tBits);
    if (tBits < old) {
        grab_state[0].id = i;
        grab_state[0].t  = t;
    }
}

void mouse_drag_pass(uint i, inout vec3 xpi, inout vec3 vi)
{
    if (pc.mouse.select_mode != MOUSE_MODE_DRAG)
        return;

    if (grab_state[0].id == 0xFFFFFFFFu)
        return;

    if (i != grab_state[0].id)
        return;

    vec3 o   = pc.mouse.ray_origin;
    vec3 dir = pc.mouse.ray_dir;

    vec3 v_to_ray = xpi - o;
    float t = grab_state[0].t;
    if (pc.mouse.depth_mode == 1u)
    {
        t *= 0.998;
        grab_state[0].t = t;
    }
    else if (pc.mouse.depth_mode == 2u)
    {
        t *= 1.002;
        grab_state[0].t = t;
    }

    vec3 c  = o + t * dir;

    xpi = c;
    vi  = vec3(0.0);
}

void main(){
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= pc.solve.count) return;
    uint i = pc.solve.base + gid;

    vec3 xi = x[i].xyz;
    vec3 vi = v[i].xyz;

    if (w[i] == 0.0) {
        xp[i] = vec4(xi, 1.0);
        v[i]  = vec4(0.0);
        return;
    }

    mouse_select_pass(i, xi);
    
    if (sim.wind_enable == 1u)
    {
        vi += delta_v[i].xyz;
        delta_v[i].xyz = vec3(0.0);
    }
    vi += sim.gravity.xyz * sim.dt;

    vec3 xpi = xi + vi * sim.dt;
    
    mouse_drag_pass(i, xpi, vi);

    xp[i] = vec4(xpi, 1.0);
    v[i] = vec4(vi, 0.0);
    
    delta_x[i] = 0.0;
    delta_y[i] = 0.0;
    delta_z[i] = 0.0;
    delta_count[i] = 0;
}
