#version 460
#extension GL_EXT_shader_atomic_float : require

#include "../common/simulation_common.glsl"

layout(local_size_x = 256) in;

void accumulate_delta(uint i, vec3 corr)
{
    atomicAdd(delta_x[i], corr.x);
    atomicAdd(delta_y[i], corr.y);
    atomicAdd(delta_z[i], corr.z);
    atomicAdd(delta_count[i], 1u);
}

bool isFinite_f(float x) { return !isnan(x) && !isinf(x); }

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= pc.solve.count) return;

    Volume vc = volumes[gid];

    uint i0 = vc.i0;
    uint i1 = vc.i1;
    uint i2 = vc.i2;
    uint i3 = vc.i3;

    float w0 = w[i0];
    float w1 = w[i1];
    float w2 = w[i2];
    float w3 = w[i3];

    float wsum = w0 + w1 + w2 + w3;
    if (wsum == 0.0) {
        volumes[gid].lambda = 0.0;
        return;
    }

    vec3 x0 = xp[i0].xyz;
    vec3 x1 = xp[i1].xyz;
    vec3 x2 = xp[i2].xyz;
    vec3 x3 = xp[i3].xyz;

    float V = dot(cross(x1 - x0, x2 - x0), (x3 - x0)) / 6.0;

    float C = V - vc.rest_volume;

    float dt = sim.dt;
    float alpha = pc.solve.compliance / (dt * dt);

    float old_lambda = vc.lambda;
    
    vec3 g0 = cross(x3 - x1, x2 - x1) / 6.0; // (1,3,2)
    vec3 g1 = cross(x2 - x0, x3 - x0) / 6.0; // (0,2,3)
    vec3 g2 = cross(x3 - x0, x1 - x0) / 6.0; // (0,3,1)
    vec3 g3 = cross(x1 - x0, x2 - x0) / 6.0; // (0,1,2)
    
    float W =
          w0 * dot(g0, g0)
        + w1 * dot(g1, g1)
        + w2 * dot(g2, g2)
        + w3 * dot(g3, g3);

    if (W < 1e-12) return;

    float s = -C / (W + alpha);

    if (w0 > 0.0) accumulate_delta(i0, g0 * (s * w0));
    if (w1 > 0.0) accumulate_delta(i1, g1 * (s * w1));
    if (w2 > 0.0) accumulate_delta(i2, g2 * (s * w2));
    if (w3 > 0.0) accumulate_delta(i3, g3 * (s * w3));
}
