    #version 460

#include "../common/simulation_common.glsl"

layout(local_size_x = 256) in;

void main() {
    uint triId = gl_GlobalInvocationID.x;
    if (triId >= sim.num_tries) return; // sim.num_tries = numTris

    uint i0 = indices[triId * 3 + 0];
    uint i1 = indices[triId * 3 + 1];
    uint i2 = indices[triId * 3 + 2];

    vec3 p0 = x[i0].xyz;
    vec3 p1 = x[i1].xyz;
    vec3 p2 = x[i2].xyz;

    vec3 e1 = p1 - p0;
    vec3 e2 = p2 - p0;
    vec3 fn = cross(e1, e2); // area-weighted
    float area2 = length(fn);
    if (area2 < 1e-8 || sim.wind_enable == 0u) return;

    float A = 0.5 * area2;
    vec3 n = fn / area2;

    float wind_force = sim.wind_force;

}
